# Generated by Django 4.2.7 on 2023-11-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='infodet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Prefer Not to Say')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='infodet',
            name='material',
        ),
        migrations.AlterField(
            model_name='infodet',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='infodet',
            name='material',
            field=models.ManyToManyField(to='homepage.material'),
        ),
    ]
